@API_BASE_URL_LOCAL = http://localhost:8000/api/v1



# Get All Categories API
GET {{API_BASE_URL_LOCAL}}/categories


GET {{API_BASE_URL_LOCAL}}/categories/slug/testing-4



# creating a new category
POST {{API_BASE_URL_LOCAL}}/categories
Content-Type: application/json

{
   "name" : "css"
}


